package:
  name: tensorly
  version: "0.5.1"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python
    - numpy
    - scipy

test:
  requires:
    - pytest

  commands:
    - TENSORLY_BACKEND='numpy' pytest -v $SP_DIR/tensorly

about:
  home: https://github.com/tensorly/tensorly/
  license: BSD
  summary: "Tensor learning in Python"
  description: |
    TensorLy is a Python library that aims at making tensor learning simple 
    and accessible. It allows to easily perform tensor decomposition, 
    tensor learning and tensor algebra. Its backend system allows to 
    seamlessly perform computation with NumPy, MXNet, PyTorch, TensorFlow,
    CuPy or JAX, and run methods at scale on CPU or GPU.

