{% set name = "tensorly" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  build:
    - python >=3.7
    - setuptools
    - pip

  run:
    - python
    - numpy
    - scipy

test:
  requires:
    - pytest

  commands:
    - TENSORLY_BACKEND='numpy' pytest -v $SP_DIR/tensorly

about:
  home: https://github.com/tensorly/tensorly/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Tensor learning in Python"
  description: |
    TensorLy is a Python library that aims at making tensor learning simple 
    and accessible. It allows to easily perform tensor decomposition, 
    tensor learning and tensor algebra. Its backend system allows to 
    seamlessly perform computation with NumPy, MXNet, PyTorch, TensorFlow,
    CuPy or JAX, and run methods at scale on CPU or GPU.
  doc_url: http://tensorly.org
  dev_url: https://github.com/tensorly/tensorly

extra:
  recipe-maintainers:
    - JeanKossaifi
